version: "1"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate && playwright install chromium && python manage.py runserver"
    env_file:
      - .env