# Generated by Django 4.2 on 2023-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Djinni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_to_vacancy", models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dou",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_id", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("location_work", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("salary_from", models.IntegerField(null=True)),
                ("salary_to", models.IntegerField(null=True)),
                ("salary", models.IntegerField(null=True)),
                ("publication_date", models.DateField(null=True)),
                ("url_to_vacancy", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FirstVacancySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spider_name", models.CharField(max_length=255, unique=True)),
                ("vacancy", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LastVacancyId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spider_name", models.CharField(max_length=50, unique=True)),
                ("vacancy_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RabotaUa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_id", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("location_work", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("salary_from", models.IntegerField(null=True)),
                ("salary_to", models.IntegerField(null=True)),
                ("salary", models.IntegerField(null=True)),
                ("publication_date", models.DateField(null=True)),
                ("company_id", models.IntegerField()),
                ("comment_to_salary", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramLastVacancyId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spider_name", models.CharField(max_length=100, unique=True)),
                ("vacancy_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkUa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_id", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("location_work", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("salary_from", models.IntegerField(null=True)),
                ("salary_to", models.IntegerField(null=True)),
                ("salary", models.IntegerField(null=True)),
                ("publication_date", models.DateField(null=True)),
                ("distance_to_center_in_km", models.FloatField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Telegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_id", models.IntegerField()),
                ("spider_name", models.CharField(max_length=255)),
                ("publication_date", models.DateTimeField()),
                ("description", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("vacancy_id", "spider_name")},
            },
        ),
    ]
