# Generated by Django 4.2 on 2023-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstvacancysession",
            name="vacancy",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
