# Generated by Django 4.2 on 2023-05-16 20:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="djinni",
            name="company_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="djinni",
            name="description",
            field=models.TextField(
                default=datetime.datetime(
                    2023, 5, 16, 20, 38, 39, 144657, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="djinni",
            name="location_work",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="publication_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="salary",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="salary_from",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="salary_to",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="title",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 5, 16, 20, 39, 6, 448590, tzinfo=datetime.timezone.utc
                ),
                max_length=300,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="djinni",
            name="vacancy_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
