# Generated by Django 4.2 on 2023-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramlastvacancyid",
            name="is_not_want",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="telegramlastvacancyid",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegramlastvacancyid",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
