# Generated by Django 4.2 on 2023-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_alter_firstvacancysession_vacancy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Djinni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=300)),
                ("company_name", models.CharField(max_length=300)),
                ("publication_date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="dou",
            name="url_to_vacancy",
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
