# Generated by Django 4.2 on 2023-05-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_djinni_company_name_djinni_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="djinni",
            name="space_work",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
