# Generated by Django 4.2 on 2023-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0003_remove_telegramlastvacancyid_is_not_want_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="is_first_vacancy_in_session",
            field=models.BooleanField(null=True),
        ),
    ]
