# Generated by Django 4.2 on 2023-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0004_telegram_is_first_vacancy_in_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstVacancySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spider_name", models.CharField(max_length=255, unique=True)),
                ("vacancy_db_id", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="telegram",
            name="is_first_vacancy_in_session",
        ),
    ]
