# Generated by Django 4.2 on 2023-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0004_rename_publication_datetime_telegram_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="djinni",
            name="url_to_vacancy",
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
