# Generated by Django 4.2 on 2023-05-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0005_firstvacancysession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstvacancysession",
            name="vacancy_db_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_vacancy_session",
                to="vacancies.telegramlastvacancyid",
            ),
        ),
    ]
