# Generated by Django 4.2 on 2023-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0005_djinni_url_to_vacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="djinni",
            name="salary",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="salary_from",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="djinni",
            name="salary_to",
            field=models.IntegerField(null=True),
        ),
    ]
