# Generated by Django 4.2 on 2023-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0006_djinni_salary_djinni_salary_from_djinni_salary_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="djinni",
            name="description",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
