# Generated by Django 4.2 on 2023-05-13 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0006_alter_firstvacancysession_vacancy_db_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firstvacancysession",
            old_name="vacancy_db_id",
            new_name="vacancy_db",
        ),
    ]
