# Generated by Django 4.2 on 2023-05-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0007_rename_vacancy_db_id_firstvacancysession_vacancy_db"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstvacancysession",
            name="vacancy_db",
        ),
        migrations.AddField(
            model_name="firstvacancysession",
            name="vacancy_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_vacancy_session",
                to="vacancies.telegramlastvacancyid",
            ),
        ),
    ]
