# Generated by Django 4.2 on 2023-05-13 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0008_remove_firstvacancysession_vacancy_db_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firstvacancysession",
            old_name="vacancy_id",
            new_name="vacancy",
        ),
    ]
