# Generated by Django 4.2 on 2023-05-13 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0009_rename_vacancy_id_firstvacancysession_vacancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstvacancysession",
            name="vacancy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_vacancy_session",
                to="vacancies.telegram",
            ),
        ),
    ]
