# Generated by Django 4.2 on 2023-05-14 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0010_alter_firstvacancysession_vacancy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegram",
            old_name="publication_date",
            new_name="publication_datetime",
        ),
    ]
