# Generated by Django 4.2 on 2023-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0011_rename_publication_date_telegram_publication_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramlastvacancyid",
            old_name="channel_name",
            new_name="spider_name",
        ),
    ]
